import React, { useState } from 'react';
import { Sparkles, ExternalLink, Lightbulb, Compass, FileText, ArrowRight } from 'lucide-react';
import { useMarketStore } from '../../store/useMarketStore';
import { ConfidenceBadge, DeltaBadge, Modal } from '../common';
import { Insight } from '../../types/insight';
import { MarketEvent } from '../../types/event';

export const TopInsightsSection: React.FC = () => {
  const { getTopInsights, events } = useMarketStore();
  const topInsights = getTopInsights(3);

  const [activeModalInsight, setActiveModalInsight] = useState<{
    insight: Insight;
    event?: MarketEvent;
  } | null>(null);

  return (
    <section className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-1 rounded-md bg-indigo-500/10 text-indigo-400">
              <Sparkles className="w-4 h-4" />
            </div>
            <h2 className="text-lg sm:text-xl font-bold text-slate-100 tracking-tight">
              Top Insights Since Your Last Visit
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Highest-conviction causal explanations generated by the Context Enrichment Engine
          </p>
        </div>

        <div className="text-xs text-slate-400 font-mono">
          Ranked by Confidence & Regulatory Authority
        </div>
      </div>

      {/* Enriched Insight Cards or Empty State */}
      {topInsights.length === 0 ? (
        <div className="p-8 rounded-2xl bg-surface border border-border text-center space-y-2">
          <div className="w-10 h-10 rounded-xl bg-surface-subtle text-slate-400 border border-border flex items-center justify-center mx-auto">
            <Lightbulb className="w-5 h-5" />
          </div>
          <h3 className="text-sm font-bold text-slate-200">No watchlist insights available.</h3>
          <p className="text-xs text-slate-400">Add stocks to your watchlist to receive causal reasoning and anomaly explanations.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-5">
          {topInsights.map((insight) => {
          const matchedEvent = events.find((e) => e.id === insight.relatedEventId);

          return (
            <div
              key={insight.id}
              className="flex flex-col justify-between bg-surface rounded-2xl border border-border/90 p-5 hover:border-indigo-500/40 hover:shadow-lg hover:shadow-indigo-500/5 transition-all duration-200 group"
            >
              <div className="space-y-3.5">
                {/* Header: Symbol, Name & Delta */}
                <div className="flex items-start justify-between gap-3 border-b border-border/60 pb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-extrabold text-base text-slate-100 font-sans tracking-tight">
                        {matchedEvent?.companyName || insight.stockSymbol}
                      </span>
                      <span className="text-xs font-mono font-medium text-slate-400 bg-surface-subtle px-1.5 py-0.5 rounded border border-border">
                        {insight.stockSymbol}
                      </span>
                    </div>

                    {matchedEvent && (
                      <div className="text-xs text-slate-300 font-medium mt-1">
                        {matchedEvent.headline}
                      </div>
                    )}
                  </div>

                  {matchedEvent && (
                    <DeltaBadge
                      value={matchedEvent.changePercent}
                      size="sm"
                    />
                  )}
                </div>

                {/* Possible Explanation (Why It Changed) */}
                <div className="p-3.5 rounded-xl bg-indigo-950/20 border border-indigo-500/20 space-y-2">
                  <div className="flex items-center justify-between text-[11px]">
                    <span className="font-semibold text-indigo-300 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
                      <Compass className="w-3.5 h-3.5 text-indigo-400" />
                      Possible Explanation
                    </span>
                    <ConfidenceBadge
                      level={insight.confidenceLevel}
                      score={insight.confidenceScore}
                    />
                  </div>

                  <p className="text-xs text-slate-200 leading-relaxed">
                    {insight.explanation}
                  </p>

                  <div className="pt-1.5 flex items-center justify-between text-[11px] text-slate-400 border-t border-indigo-500/15">
                    <span>Source:</span>
                    <a
                      href={insight.sourceUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-medium text-indigo-300 hover:text-indigo-200 flex items-center gap-1"
                    >
                      <span>{insight.sourceName}</span>
                      <ExternalLink className="w-3 h-3 text-indigo-400" />
                    </a>
                  </div>
                </div>

                {/* Why It Matters */}
                <div className="p-3 rounded-xl bg-surface-subtle border border-border/70 space-y-1">
                  <div className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-amber-400">
                    <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
                    <span>Why It Matters</span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed">
                    {insight.whyItMatters}
                  </p>
                </div>
              </div>

              {/* Card Footer Button */}
              <div className="mt-4 pt-3 border-t border-border/60">
                <button
                  onClick={() =>
                    setActiveModalInsight({
                      insight,
                      event: matchedEvent,
                    })
                  }
                  className="w-full py-2 px-3 rounded-lg bg-surface-hover hover:bg-surface-active text-xs font-semibold text-slate-200 hover:text-white flex items-center justify-center gap-1.5 border border-border transition-colors group/btn"
                >
                  <FileText className="w-3.5 h-3.5 text-slate-400 group-hover/btn:text-indigo-400 transition-colors" />
                  <span>View Full Insight</span>
                  <ArrowRight className="w-3.5 h-3.5 ml-0.5 text-slate-400 group-hover/btn:translate-x-0.5 transition-transform" />
                </button>
              </div>
            </div>
          );
        })}
        </div>
      )}

      {/* Accessible Detail Modal for View Full Insight */}
      {activeModalInsight && (
        <Modal
          isOpen={Boolean(activeModalInsight)}
          onClose={() => setActiveModalInsight(null)}
          title={`${activeModalInsight.insight.stockSymbol} — Causal Intelligence Dossier`}
          subtitle={`Attribution Generated via ${activeModalInsight.insight.sourceName}`}
          maxWidth="lg"
          footer={
            <div className="w-full flex items-center justify-between">
              <span className="text-xs text-slate-400">
                Confidence: {Math.round(activeModalInsight.insight.confidenceScore * 100)}%
              </span>
              <button
                onClick={() => setActiveModalInsight(null)}
                className="px-4 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-xs font-semibold text-white transition-colors"
              >
                Close
              </button>
            </div>
          }
        >
          <div className="space-y-4 text-xs sm:text-sm">
            {/* Header info */}
            <div className="p-3.5 rounded-xl bg-surface-subtle border border-border flex items-center justify-between">
              <div>
                <div className="font-bold text-slate-100 text-base">
                  {activeModalInsight.event?.companyName || activeModalInsight.insight.stockSymbol}
                </div>
                <div className="text-xs text-slate-400 mt-0.5">
                  {activeModalInsight.event?.headline}
                </div>
              </div>
              <ConfidenceBadge
                level={activeModalInsight.insight.confidenceLevel}
                score={activeModalInsight.insight.confidenceScore}
              />
            </div>

            {/* Detailed Explanation */}
            <div className="space-y-1.5">
              <div className="text-xs font-semibold uppercase text-indigo-400 tracking-wider">
                Full Causal Attribution
              </div>
              <p className="text-slate-200 leading-relaxed text-xs sm:text-sm bg-surface p-3.5 rounded-xl border border-border">
                {activeModalInsight.insight.explanation}
              </p>
            </div>

            {/* Key Disclosed Metrics */}
            {activeModalInsight.insight.keyMetrics && (
              <div className="space-y-1.5">
                <div className="text-xs font-semibold uppercase text-slate-400 tracking-wider">
                  Disclosed Metrics & Data Points
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {Object.entries(activeModalInsight.insight.keyMetrics).map(
                    ([key, val]) => (
                      <div
                        key={key}
                        className="p-2.5 rounded-lg bg-surface border border-border font-mono"
                      >
                        <div className="text-[10px] text-slate-400">{key}</div>
                        <div className="text-xs font-semibold text-emerald-400 mt-0.5">
                          {val}
                        </div>
                      </div>
                    )
                  )}
                </div>
              </div>
            )}

            {/* Strategic Impact */}
            <div className="space-y-1.5">
              <div className="text-xs font-semibold uppercase text-amber-400 tracking-wider">
                Portfolio & Market Strategic Implication
              </div>
              <p className="text-slate-300 leading-relaxed text-xs bg-amber-500/5 border border-amber-500/20 p-3.5 rounded-xl">
                {activeModalInsight.insight.whyItMatters}
              </p>
            </div>

            {/* Source Meta */}
            <div className="p-3 rounded-lg bg-surface border border-border flex items-center justify-between text-xs text-slate-400 font-mono">
              <span>Source Authority: {activeModalInsight.insight.sourceName}</span>
              <a
                href={activeModalInsight.insight.sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-400 hover:text-indigo-300 flex items-center gap-1"
              >
                <span>Read Original Filing/Article</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          </div>
        </Modal>
      )}
    </section>
  );
};
